runtime: nodejs18 # or another supported version

service: team3-frontend
service_account: team3-390@rice-comp-539-spring-2022.iam.gserviceaccount.com

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /
    static_dir: build
  - url: /static
    static_dir: build/static


# [END gae_flex_quickstart_yaml]
